version: '3.8'

services:
  mcp-brave-search:
    container_name: agent-framework-mcp-brave-search-1
    image: mcp/brave-search:latest
    environment:
      - BRAVE_API_KEY=${BRAVE_API_KEY}
    ports:
      - "8111:8080"
    restart: unless-stopped
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
